Implement indexing for Align<T>
ash-rs/ash pull request #373
Opened 2021-02-20 11:31 UTC by AidanConnelly

Small speculative PR.

This is useful for a variety of situations where the alternative, recreating the Align<T> with the relevant start and sizes, would involve the need to lug around information already stored in Align<T> itself.

2021-02-20 11:49 UTC, MarijnS95 requested changes
Would it make sense to implement [`std::ops::index`](https://doc.rust-lang.org/std/ops/trait.Index.html) at some point?

Shouldn't this function perform any kind of bounds checking? If not, perhaps that should be mentioned in `# Safety` docs?

2021-02-20 11:49 UTC, MarijnS95 commented on ash/src/util.rs
> +            _m: self._m,
You should be able to use struct update syntax to carry `elem_size` and `_m` over:

```suggestion
            ptr: (self.ptr as *mut u8).offset((index.start as u64 * self.elem_size) as isize) as *mut c_void,
            size: (index.end - index.start) as u64 * self.elem_size as u64,
            ..*self
```

2021-02-20 11:49 UTC, MarijnS95 commented on ash/src/util.rs
> +            ptr: (self.ptr as *mut u8).offset((index.start as u64 * self.elem_size) as isize) as *mut c_void,
Afaik `.offset` is implemented for `*mut c_void` and jumps by a byte-size of `1` - the cast to `*mut u8` and back to `*mut c_void` should not be necessary.

2021-02-20 11:49 UTC, MarijnS95 commented on ash/src/util.rs
> +            size: (index.end - index.start) as u64 * self.elem_size as u64,
`elem_size` is a `vk::DeviceSize` which should already be an alias to `u64`?

2021-12-21 10:33 UTC, MarijnS95 commented
@AidanConnelly Are you still planning to update this PR?

2024-03-24 16:12 UTC, Ralith commented
Closing as this has been abandoned.

2024-03-24 16:12 UTC, closed without merging