generator: Do not generate code for "disabled" extensions
ash-rs/ash pull request #448
Opened 2021-06-07 07:57 UTC by MarijnS95

It is unlikely that disabled, reserved extensions (without naming whatsoever) are used through Ash bindings generated from Vulkan-Headers releases, and are best ignored to reduce diff noise and spurious issues [1] with unfinished extension definitions.

[1]: https://github.com/KhronosGroup/Vulkan-Docs/issues/1549

---

Let me know if someone is using our bindings to access in-development extensions through these means though! (But in that case I expect a local substitution in `vk.xml` + regeneration...)

2021-06-07 08:05 UTC, MarijnS95 commented
Whoops, should have ran `cargo check`, this fails to compile for the same reason as https://github.com/MaikKlein/ash/pull/417#issuecomment-855208839 :/

We should either:

1. Exempt some well-defined but disabled extensions from this check (only `VK_ANDROID_native_buffer` for now);
2. Fold extension-types with their extension (scheduled for the new generator as it's quite an overhaul, see linked comment above);
3. Not do this at all, accept the numbered extensions and skip `1.2.180` until `vk.xml` is fixed (or - unlikely - skip the broken extension if someone absolutely needs `1.2.180`).

2022-12-11 05:05 UTC, Ralith requested changes
Looks like some unrelated updates got mixed in?

2022-12-11 19:18 UTC, MarijnS95 commented
Looks like I either forgot to re-sync the submodule to `1.3.235`, _or_ base this on top of #688. It's self-supporting now on `1.3.235`.

2022-12-12 00:35 UTC, Ralith approved these changes
Nice!

2022-12-12 00:36 UTC, merged