Add Fuchsia support
ash-rs/ash pull request #626
Opened 2022-05-26 20:25 UTC by abarth

Use the proper name for `libvulkan.so` on Fuchsia.

2022-05-26 20:26 UTC, MarijnS95 requested changes

2022-05-26 20:26 UTC, MarijnS95 commented on ash/src/entry.rs
> +            not(any(target_os = "macos", target_os = "ios", target_os = "android", target = "fuchsia"))
```suggestion
            not(any(target_os = "macos", target_os = "ios", target_os = "android", target_os = "fuchsia"))
```

?

2022-05-26 20:28 UTC, MarijnS95 commented
https://doc.rust-lang.org/reference/conditional-compilation.html#target_os I'm surprised the official docs don't mention the existence of `fuchsia` :/

2022-05-27 00:47 UTC, Ralith approved these changes
Fuchsia doesn't do the unixy `.so.$MAJOR` thing? Interesting; is this documented anywhere?

2022-05-27 00:49 UTC, Ralith commented
Note that if you build ash with `features = ["linked"], default-features = false`, existing versions of ash should Just Work, and be less fragile at runtime besides.

2022-05-27 01:04 UTC, abarth commented
> Fuchsia doesn't do the unixy .so.$MAJOR thing?

Yes, we do that for most shared libraries.  I'm not sure why `libvulkan.so` doesn't have a `.$MAJOR` suffix.

> Interesting; is this documented anywhere?

https://fuchsia.dev/fuchsia-src/development/graphics/magma/concepts/vulkan?hl=en#buildtime_dependencies

> Any way we can sensibly cover this in CI?

Not yet.  We're working on that as part of our quest for Tier 1 support in Rust.

> Note that if you build ash with features = ["linked"], default-features = false, existing versions of ash should Just Work, and be less fragile at runtime besides.

Ok, I'll give that a try.

2022-05-27 01:08 UTC, Ralith commented
> Yes, we do that for most shared libraries. I'm not sure why libvulkan.so doesn't have a .$MAJOR suffix.

Hmm, are you using the standard Khronos Vulkan loader? This may be a bug in the upstream build system, if so. I'm not entirely clear on the significance of respecting that pattern vs. not, but I figure it's probably worth being consistent with the system at large.

2024-03-24 18:24 UTC, MarijnS95 commented
@abarth any update on not using/having a `.MAJOR` suffix on Fuchsia?

2024-03-24 18:25 UTC, MarijnS95 approved these changes

2024-04-01 09:21 UTC, MarijnS95 commented
Looking at the linked Fuchsia docs it's still `libvulkan.so` without `.MAJOR` suffix; I'll merge this in for the `0.38` release.

2024-04-01 09:22 UTC, merged

2024-04-01 09:25 UTC, MarijnS95 commented
For `cargo:rustc-link-lib=vulkan` under the `linked` feature, this should keep working OOTB :)